<?php

namespace App\Filament\Resources\Drivers\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class DriverForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->disabled(fn (): bool => auth()->user()?->hasRole('readonly') ?? false)
            ->components([
                Section::make(__('admin.sections.driver_details'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('name')
                                ->label(__('admin.labels.name'))
                                ->required()
                                ->maxLength(120),
                            TextInput::make('phone')
                                ->label(__('admin.labels.phone'))
                                ->maxLength(30),
                            TextInput::make('email')
                                ->label(__('admin.labels.email'))
                                ->email()
                                ->maxLength(150),
                            Toggle::make('active')
                                ->label(__('admin.labels.active'))
                                ->default(true),
                            Toggle::make('blacklisted')
                                ->label(__('admin.labels.blacklist')),
                            Toggle::make('on_vacation')
                                ->label(__('admin.labels.holidays')),
                        ]),
                    ]),
                Section::make(__('admin.sections.personal_data'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('nif')
                                ->label(__('admin.labels.nif'))
                                ->maxLength(20),
                            DatePicker::make('birth_date')
                                ->label(__('admin.labels.birth_date')),
                            TextInput::make('nationality')
                                ->label(__('admin.labels.nationality'))
                                ->maxLength(80),
                            TextInput::make('marital_status')
                                ->label(__('admin.labels.marital_status'))
                                ->maxLength(80),
                        ]),
                    ]),
                Section::make(__('admin.sections.address_notes'))
                    ->schema([
                        Textarea::make('address')
                            ->label(__('admin.labels.address'))
                            ->columnSpanFull(),
                        Textarea::make('notes')
                            ->label(__('admin.labels.notes'))
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.sections.documentation'))
                    ->schema([
                        FileUpload::make('documentation')
                            ->label(__('admin.labels.documentation'))
                            ->multiple()
                            ->reorderable()
                            ->downloadable()
                            ->openable()
                            ->columnSpanFull(),
                    ]),
                Section::make(__('admin.sections.company'))
                    ->schema([
                        Select::make('company_id')
                            ->label(__('admin.labels.company'))
                            ->relationship('company', 'name')
                            ->searchable()
                            ->preload(),
                    ]),
                Section::make(__('admin.sections.identification'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('identity_document_type')
                                ->label(__('admin.labels.id_document_type'))
                                ->maxLength(80),
                            TextInput::make('identity_document_number')
                                ->label(__('admin.labels.id_document_number'))
                                ->maxLength(80),
                            DatePicker::make('identity_document_valid_until')
                                ->label(__('admin.labels.validity')),
                        ]),
                    ]),
                Section::make(__('admin.sections.social_security'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('sns_number')
                                ->label(__('admin.labels.sns'))
                                ->maxLength(40),
                            TextInput::make('niss_number')
                                ->label(__('admin.labels.niss'))
                                ->maxLength(40),
                        ]),
                    ]),
                Section::make(__('admin.sections.driving_license'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('driving_license_number')
                                ->label(__('admin.labels.driving_license'))
                                ->maxLength(60),
                            DatePicker::make('driving_license_issued_at')
                                ->label(__('admin.labels.issued_at')),
                            DatePicker::make('driving_license_valid_until')
                                ->label(__('admin.labels.validity')),
                            TextInput::make('driving_license_category')
                                ->label(__('admin.labels.category'))
                                ->maxLength(20),
                        ]),
                    ]),
                Section::make(__('admin.sections.tvde_certificate'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('tvde_certificate_number')
                                ->label(__('admin.labels.tvde_certificate_number'))
                                ->maxLength(60),
                            DatePicker::make('tvde_certificate_valid_until')
                                ->label(__('admin.labels.validity')),
                        ]),
                    ]),
                Section::make(__('admin.sections.platforms'))
                    ->schema([
                        Grid::make(2)->schema([
                            Toggle::make('platform_uber')
                                ->label(__('admin.labels.uber')),
                            Toggle::make('platform_bolt')
                                ->label(__('admin.labels.bolt')),
                            TextInput::make('platform_other')
                                ->label(__('admin.labels.other'))
                                ->maxLength(120),
                        ]),
                    ]),
                Section::make(__('admin.sections.emergency_contact'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('emergency_contact_name')
                                ->label(__('admin.labels.name'))
                                ->maxLength(120),
                            TextInput::make('emergency_contact_phone')
                                ->label(__('admin.labels.phone'))
                                ->maxLength(30),
                        ]),
                    ]),
                Section::make(__('admin.sections.bank_details'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('bank_account_holder')
                                ->label(__('admin.labels.account_holder'))
                                ->maxLength(120),
                            TextInput::make('bank_iban')
                                ->label(__('admin.labels.iban'))
                                ->maxLength(34),
                        ]),
                    ]),
                Section::make(__('admin.sections.deposit'))
                    ->schema([
                        Grid::make(2)->schema([
                            TextInput::make('deposit_amount')
                                ->label(__('admin.labels.value'))
                                ->numeric(),
                            DatePicker::make('deposit_paid_at')
                                ->label(__('admin.labels.paid_on')),
                            TextInput::make('deposit_payment_method')
                                ->label(__('admin.labels.payment_method'))
                                ->maxLength(60),
                        ]),
                    ]),
                Section::make(__('admin.sections.activity'))
                    ->schema([
                        Grid::make(2)->schema([
                            DatePicker::make('activity_started_at')
                                ->label(__('admin.labels.start_date')),
                            DatePicker::make('activity_ended_at')
                                ->label(__('admin.labels.end_date')),
                        ]),
                    ]),
            ]);
    }
}
